# This script processes the data into a dataset usable by the training algorithm

## Import pandas and numpy

In [165]:
import pandas as pd
import numpy as np

## Read our data from csv to pandas datafram

In [187]:
df = pd.read_csv("../data/agg_processed.csv")
df

,TLS_SNI,0,1,2,3,4,5,6,7,8,...,21,22,23,24,25,26,27,28,29,class
0,ecs.office.com,727,-99,798,-1380,-1380,-527,-1380,-1380,74,...,0,0,0,0,0,0,0,0,0,other
1,sah-9f2a2e75-hap21.epmgmt.checkpoint.com,517,-1380,-1380,-1380,-446,126,-51,1380,788,...,0,0,0,0,0,0,0,0,0,other
2,sah-9f2a2e75-hap21.epmgmt.checkpoint.com,517,-1380,-1380,-1380,-446,126,-51,1380,788,...,0,0,0,0,0,0,0,0,0,other
3,cloud.sa.cz,517,-1380,-1380,-571,80,-287,-287,1021,-1113,...,0,0,0,0,0,0,0,0,0,other
4,cloud.sa.cz,517,-1380,-1380,-571,80,-287,-287,1030,-1109,...,0,0,0,0,0,0,0,0,0,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12338,registry.npmjs.org,659,-147,6,45,256,-1398,-1408,-1388,-1408,...,0,0,0,0,0,0,0,0,0,other
12339,pypi.org,457,-1408,6,-1408,-1408,-831,74,220,-1408,...,-24,80,0,0,0,0,0,0,0,other
12340,default.exp-tas.com,517,-99,344,-1420,-1420,-1338,614,-459,-1420,...,0,0,0,0,0,0,0,0,0,other
12341,westus-0.in.applicationinsights.azure.com,517,-99,351,-1408,-1408,-1408,-183,711,-103,...,0,0,0,0,0,0,0,0,0,other
12342,copilot-telemetry.githubusercontent.com,517,-1408,-1408,-1270,1408,541,-79,-79,-587,...,0,0,0,0,0,0,0,0,0,other

## Extract only rows with destination port of 443

In [171]:
df = df[df['uint16 DST_PORT'] == 443]
df

,Unnamed: 0,uint64 BYTES,uint64 BYTES_REV,uint64 LINK_BIT_FIELD,time TIME_FIRST,time TIME_LAST,uint32 PACKETS,uint32 PACKETS_REV,uint16 DST_PORT,uint16 SRC_PORT,...,uint32* D_PHISTS_SIZES,uint32* SBI_BRST_BYTES,uint32* SBI_BRST_PACKETS,uint32* S_PHISTS_IPT,uint32* S_PHISTS_SIZES,time* DBI_BRST_TIME_START,time* DBI_BRST_TIME_STOP,time* PPI_PKT_TIMES,time* SBI_BRST_TIME_START,time* SBI_BRST_TIME_STOP
0,0,889,4577,2,2025-03-12T06:48:54.498815,2025-03-12T06:48:54.561756,7,7,443,22954,...,[0|0|0|0|0|2|0|3],[],[],[0|0|1|0|0|0|0|0],[0|0|0|1|0|0|1|0],[],[],[2025-03-12T06:48:54.516000|2025-03-12T06:48:5...,[],[]
1,1,3256,5623,512,2025-03-12T06:48:52.345630,2025-03-12T06:48:54.550206,19,16,443,49903,...,[0|2|2|0|2|2|1|2],[],[],[5|0|1|0|0|0|0|1],[0|2|2|1|0|1|1|1],[],[],[2025-03-12T06:48:52.349000|2025-03-12T06:48:5...,[],[]
2,2,6605,1846,512,2025-03-12T06:48:52.951556,2025-03-12T06:48:53.139615,17,16,443,15439,...,[0|0|1|1|3|1|0|0],[],[],[8|2|0|1|0|0|0|0],[0|1|3|2|0|0|2|4],[],[],[2025-03-12T06:48:52.957000|2025-03-12T06:48:5...,[],[]
3,3,1782,6928,512,2025-03-12T06:48:53.119376,2025-03-12T06:48:53.353080,15,17,443,58020,...,[0|1|1|0|0|2|2|3],[],[],[5|1|0|0|0|0|0|0],[0|2|2|1|0|2|0|0],[],[],[2025-03-12T06:48:53.123000|2025-03-12T06:48:5...,[],[]
4,4,10201,17126,512,2025-03-12T06:48:24.254575,2025-03-12T06:48:54.874323,66,82,443,65138,...,[0|1|11|15|6|7|6|3],[],[],[11|3|6|4|3|2|0|7],[0|1|14|11|5|2|3|1],[],[],[2025-03-12T06:48:24.260000|2025-03-12T06:48:2...,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031090,1031090,3011,4616,2,2025-03-12T07:18:19.807107,2025-03-12T07:18:19.861793,13,13,443,57154,...,[0|2|1|0|1|1|1|2],[],[],[5|0|0|0|0|0|0|0],[0|2|0|1|0|1|1|1],[],[],[2025-03-12T07:18:19.811000|2025-03-12T07:18:1...,[],[]
1031091,1031091,5699,6985,2,2025-03-12T07:17:19.911057,2025-03-12T07:18:21.944506,14,14,443,19592,...,[0|0|2|1|0|1|1|4],[],[],[3|2|0|0|0|0|0|0],[0|0|0|1|1|0|1|3],[],[],[2025-03-12T07:17:19.932000|2025-03-12T07:17:1...,[],[]
1031092,1031092,44106,1136275,16,2025-03-12T07:18:15.502358,2025-03-12T07:18:16.180829,804,788,443,52955,...,[0|2|1|4|5|10|12|749],[],[],[1|5|0|0|0|0|1|0],[0|1|0|1|0|6|0|0],[],[],[2025-03-12T07:18:15.512000|2025-03-12T07:18:1...,[],[]
1031093,1031093,36080,9196,4,2025-03-12T07:14:11.339818,2025-03-12T07:18:41.676236,58,58,443,64009,...,[0|9|5|1|14|3|0|2],[],[],[36|0|0|1|0|0|0|6],[6|1|0|12|0|2|1|22],[],[],[2025-03-12T07:14:11.375000|2025-03-12T07:14:1...,[],[]
1031094,1031094,3495,5069,4,2025-03-12T07:18:10.447110,2025-03-12T07:18:10.506460,10,8,443,58500,...,[1011525061|1466421557|1021180081|241684789|31...,[],[],[1677747200|3355468800|3657437696|3959427584|4...,[1778390529|1778384897|1778384897|2315264001|2...,[],[],[2094-05-28T07:02:25.914064|2034-11-11T11:26:5...,[],[]

## Remove duplicate rows

In [172]:
df = df.drop_duplicates()
df

,Unnamed: 0,uint64 BYTES,uint64 BYTES_REV,uint64 LINK_BIT_FIELD,time TIME_FIRST,time TIME_LAST,uint32 PACKETS,uint32 PACKETS_REV,uint16 DST_PORT,uint16 SRC_PORT,...,uint32* D_PHISTS_SIZES,uint32* SBI_BRST_BYTES,uint32* SBI_BRST_PACKETS,uint32* S_PHISTS_IPT,uint32* S_PHISTS_SIZES,time* DBI_BRST_TIME_START,time* DBI_BRST_TIME_STOP,time* PPI_PKT_TIMES,time* SBI_BRST_TIME_START,time* SBI_BRST_TIME_STOP
0,0,889,4577,2,2025-03-12T06:48:54.498815,2025-03-12T06:48:54.561756,7,7,443,22954,...,[0|0|0|0|0|2|0|3],[],[],[0|0|1|0|0|0|0|0],[0|0|0|1|0|0|1|0],[],[],[2025-03-12T06:48:54.516000|2025-03-12T06:48:5...,[],[]
1,1,3256,5623,512,2025-03-12T06:48:52.345630,2025-03-12T06:48:54.550206,19,16,443,49903,...,[0|2|2|0|2|2|1|2],[],[],[5|0|1|0|0|0|0|1],[0|2|2|1|0|1|1|1],[],[],[2025-03-12T06:48:52.349000|2025-03-12T06:48:5...,[],[]
2,2,6605,1846,512,2025-03-12T06:48:52.951556,2025-03-12T06:48:53.139615,17,16,443,15439,...,[0|0|1|1|3|1|0|0],[],[],[8|2|0|1|0|0|0|0],[0|1|3|2|0|0|2|4],[],[],[2025-03-12T06:48:52.957000|2025-03-12T06:48:5...,[],[]
3,3,1782,6928,512,2025-03-12T06:48:53.119376,2025-03-12T06:48:53.353080,15,17,443,58020,...,[0|1|1|0|0|2|2|3],[],[],[5|1|0|0|0|0|0|0],[0|2|2|1|0|2|0|0],[],[],[2025-03-12T06:48:53.123000|2025-03-12T06:48:5...,[],[]
4,4,10201,17126,512,2025-03-12T06:48:24.254575,2025-03-12T06:48:54.874323,66,82,443,65138,...,[0|1|11|15|6|7|6|3],[],[],[11|3|6|4|3|2|0|7],[0|1|14|11|5|2|3|1],[],[],[2025-03-12T06:48:24.260000|2025-03-12T06:48:2...,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031090,1031090,3011,4616,2,2025-03-12T07:18:19.807107,2025-03-12T07:18:19.861793,13,13,443,57154,...,[0|2|1|0|1|1|1|2],[],[],[5|0|0|0|0|0|0|0],[0|2|0|1|0|1|1|1],[],[],[2025-03-12T07:18:19.811000|2025-03-12T07:18:1...,[],[]
1031091,1031091,5699,6985,2,2025-03-12T07:17:19.911057,2025-03-12T07:18:21.944506,14,14,443,19592,...,[0|0|2|1|0|1|1|4],[],[],[3|2|0|0|0|0|0|0],[0|0|0|1|1|0|1|3],[],[],[2025-03-12T07:17:19.932000|2025-03-12T07:17:1...,[],[]
1031092,1031092,44106,1136275,16,2025-03-12T07:18:15.502358,2025-03-12T07:18:16.180829,804,788,443,52955,...,[0|2|1|4|5|10|12|749],[],[],[1|5|0|0|0|0|1|0],[0|1|0|1|0|6|0|0],[],[],[2025-03-12T07:18:15.512000|2025-03-12T07:18:1...,[],[]
1031093,1031093,36080,9196,4,2025-03-12T07:14:11.339818,2025-03-12T07:18:41.676236,58,58,443,64009,...,[0|9|5|1|14|3|0|2],[],[],[36|0|0|1|0|0|0|6],[6|1|0|12|0|2|1|22],[],[],[2025-03-12T07:14:11.375000|2025-03-12T07:14:1...,[],[]
1031094,1031094,3495,5069,4,2025-03-12T07:18:10.447110,2025-03-12T07:18:10.506460,10,8,443,58500,...,[1011525061|1466421557|1021180081|241684789|31...,[],[],[1677747200|3355468800|3657437696|3959427584|4...,[1778390529|1778384897|1778384897|2315264001|2...,[],[],[2094-05-28T07:02:25.914064|2034-11-11T11:26:5...,[],[]

## See our columns

In [161]:
df.columns

Index(['Unnamed: 0', 'TLS_SNI', 'PKT_DIRECTIONS', 'PKT_LENGTHS'], dtype='object')

## Choose the columns we need       
**Which is *TLS_SNI*, which contains our domain (service) and will be used for annotattion, *PPI_PKT_DIECTIONS*, which contains 1 or -1 for each packet in the flow depending on the direction of the packet, and *PPI_PKT_LENGTHS*, which contains the lengths of first 30 packets**           
**We will also rename the columns so the work with them will be easier**

In [173]:
df = df[['string TLS_SNI', 'int8* PPI_PKT_DIRECTIONS', 'uint16* PPI_PKT_LENGTHS']]
df = df.rename(columns={'string TLS_SNI': 'TLS_SNI', 'int8* PPI_PKT_DIRECTIONS': "PKT_DIRECTIONS", "uint16* PPI_PKT_LENGTHS": "PKT_LENGTHS"})
df

,TLS_SNI,PKT_DIRECTIONS,PKT_LENGTHS
0,d11-a.sdn.cz,[1|-1|-1|-1|1|-1|-1],[517|1240|1240|1231|80|287|287]
1,firebaselogging-pa.googleapis.com,[1|-1|-1|-1|-1|1|-1|1|-1|1|1|-1|-1|-1|-1|-1|1|...,[517|1368|1368|457|457|64|614|272|31|1234|31|2...
2,geller-pa.googleapis.com,[1|-1|1|-1|1|-1|1|1|1|1|1|1|-1|-1|-1|1|1|1],[517|156|51|69|68|38|733|1024|1024|1024|1024|1...
3,shepherd.avcdn.net,[1|-1|-1|-1|-1|1|1|-1|-1|1|-1|-1|-1|1|1|1],[463|1412|1412|1412|305|80|485|618|31|31|370|6...
4,gew4-spclient.spotify.com,[1|-1|1|-1|1|1|-1|1|1|-1|-1|-1|1|1|1|-1|-1|-1|...,[561|212|64|586|46|37|31|35|871|192|323|39|31|...
...,...,...,...
1031090,epwa.europarl.europa.eu,[1|-1|-1|-1|1|1|1|-1|-1|-1|1|1|-1|-1],[517|1238|1238|822|64|1238|442|179|62|31|31|31...
1031091,winatp-gw-weu.microsoft.com,[1|-1|-1|-1|-1|-1|-1|1|-1|1|1|1|1|-1|-1],[212|1330|1330|1330|106|1330|589|93|51|1380|13...
1031092,honzik.avcdn.net,[1|-1|-1|-1|1|1|-1|-1|-1|-1|-1|-1|-1|-1|-1|-1|...,[461|1448|1448|621|80|345|287|287|1448|1448|14...
1031093,prebid-server.rubiconproject.com,[1|-1|-1|-1|-1|-1|-1|-1|1|-1|-1|1|-1|-1|-1|1|1...,[552|133|41|1400|1364|246|286|74|80|303|303|92...
1031094,zN=5gQ=,[0|0|0|0|0|0|0|0|0|0|0],[53557|7783|60293|15697|53557|7783|60293|15697...

**These cells are here only for file aggreggation**

In [44]:
agg = df
agg

,TLS_SNI,PKT_DIRECTIONS,PKT_LENGTHS
3,NaN,[1],[1]
4,NaN,[],[]
13,NaN,[1],[1]
14,NaN,[1|1|-1|1|1|-1|-1|-1],[1380|714|260|80|751|303|455|24]
16,NaN,[1|1|-1|-1|-1|-1],[1|443|1380|1380|66|1380]
...,...,...,...
378,NaN,[1|1|1|-1|-1|-1|-1|-1|1|1|1|1|-1|-1|-1|-1|1|-1...,[1250|1250|79|40|1250|1250|291|952|1250|31|124...
379,NaN,[1|1|1|-1|-1|1|-1|-1|1|-1],[1244|1250|321|27|24|32|1186|90|35|24]
380,NaN,[1|1|-1|1|1|1|-1|-1|-1],[1380|677|240|64|1380|32|271|778|24]
381,NaN,[1|1|-1|1|1|1|-1|-1|-1|-1|1|1|1|-1|-1|-1|-1|1|...,[1380|726|260|80|928|921|303|1380|1066|1066|92...
383,NaN,[1|1|-1|-1|-1|-1|1|1|1|1|1|1|1|-1|-1|1|-1|-1|-...,[1380|559|1380|1380|1380|1302|126|99|1380|242|...

In [135]:
agg = pd.concat([agg, df])
agg

,TLS_SNI,PKT_DIRECTIONS,PKT_LENGTHS
3,NaN,[1],[1]
4,NaN,[],[]
13,NaN,[1],[1]
14,NaN,[1|1|-1|1|1|-1|-1|-1],[1380|714|260|80|751|303|455|24]
16,NaN,[1|1|-1|-1|-1|-1],[1|443|1380|1380|66|1380]
...,...,...,...
4105,NaN,[],[]
4109,NaN,[],[]
4111,NaN,[1|1|-1|-1|-1|1|-1|-1|-1],[1408|322|1408|1408|360|64|179|62|24]
4113,NaN,[],[]
4116,NaN,[1|-1|1|-1|-1|1|-1|-1|-1|1|1|1|1|1|1|-1|-1|1|1...,[1200|1200|1200|1200|1200|39|1200|1200|762|39|...

In [163]:
agg.to_csv('../data/agg.csv', index=False)

In [137]:
df = agg

In [150]:
df = df[['TLS_SNI', 'PKT_DIRECTIONS', 'PKT_LENGTHS']]

## Split packet directions into 30 independent columns, each containing either None (No packet there) or 1 or -1

In [174]:
df = df.join(df['PKT_DIRECTIONS'].str.replace("[", "").str.replace("]", "").str.split("|", expand=True)).drop('PKT_DIRECTIONS', axis=1)
df

,TLS_SNI,PKT_LENGTHS,0,1,2,3,4,5,6,7,...,20,21,22,23,24,25,26,27,28,29
0,d11-a.sdn.cz,[517|1240|1240|1231|80|287|287],1,-1,-1,-1,1,-1,-1,None,...,None,None,None,None,None,None,None,None,None,None
1,firebaselogging-pa.googleapis.com,[517|1368|1368|457|457|64|614|272|31|1234|31|2...,1,-1,-1,-1,-1,1,-1,1,...,None,None,None,None,None,None,None,None,None,None
2,geller-pa.googleapis.com,[517|156|51|69|68|38|733|1024|1024|1024|1024|1...,1,-1,1,-1,1,-1,1,1,...,None,None,None,None,None,None,None,None,None,None
3,shepherd.avcdn.net,[463|1412|1412|1412|305|80|485|618|31|31|370|6...,1,-1,-1,-1,-1,1,1,-1,...,None,None,None,None,None,None,None,None,None,None
4,gew4-spclient.spotify.com,[561|212|64|586|46|37|31|35|871|192|323|39|31|...,1,-1,1,-1,1,1,-1,1,...,-1,-1,-1,-1,1,-1,1,1,-1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031090,epwa.europarl.europa.eu,[517|1238|1238|822|64|1238|442|179|62|31|31|31...,1,-1,-1,-1,1,1,1,-1,...,None,None,None,None,None,None,None,None,None,None
1031091,winatp-gw-weu.microsoft.com,[212|1330|1330|1330|106|1330|589|93|51|1380|13...,1,-1,-1,-1,-1,-1,-1,1,...,None,None,None,None,None,None,None,None,None,None
1031092,honzik.avcdn.net,[461|1448|1448|621|80|345|287|287|1448|1448|14...,1,-1,-1,-1,1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
1031093,prebid-server.rubiconproject.com,[552|133|41|1400|1364|246|286|74|80|303|303|92...,1,-1,-1,-1,-1,-1,-1,-1,...,1,1,1,1,1,1,1,1,1,1
1031094,zN=5gQ=,[53557|7783|60293|15697|53557|7783|60293|15697...,0,0,0,0,0,0,0,0,...,None,None,None,None,None,None,None,None,None,None

## We now need to drop the packets, which have an empty string in the first packet direction, because that means, that there is no packet in the flow

In [175]:
df = df.drop(df[0][df[0] == ''].index)
df

,TLS_SNI,PKT_LENGTHS,0,1,2,3,4,5,6,7,...,20,21,22,23,24,25,26,27,28,29
0,d11-a.sdn.cz,[517|1240|1240|1231|80|287|287],1,-1,-1,-1,1,-1,-1,None,...,None,None,None,None,None,None,None,None,None,None
1,firebaselogging-pa.googleapis.com,[517|1368|1368|457|457|64|614|272|31|1234|31|2...,1,-1,-1,-1,-1,1,-1,1,...,None,None,None,None,None,None,None,None,None,None
2,geller-pa.googleapis.com,[517|156|51|69|68|38|733|1024|1024|1024|1024|1...,1,-1,1,-1,1,-1,1,1,...,None,None,None,None,None,None,None,None,None,None
3,shepherd.avcdn.net,[463|1412|1412|1412|305|80|485|618|31|31|370|6...,1,-1,-1,-1,-1,1,1,-1,...,None,None,None,None,None,None,None,None,None,None
4,gew4-spclient.spotify.com,[561|212|64|586|46|37|31|35|871|192|323|39|31|...,1,-1,1,-1,1,1,-1,1,...,-1,-1,-1,-1,1,-1,1,1,-1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031090,epwa.europarl.europa.eu,[517|1238|1238|822|64|1238|442|179|62|31|31|31...,1,-1,-1,-1,1,1,1,-1,...,None,None,None,None,None,None,None,None,None,None
1031091,winatp-gw-weu.microsoft.com,[212|1330|1330|1330|106|1330|589|93|51|1380|13...,1,-1,-1,-1,-1,-1,-1,1,...,None,None,None,None,None,None,None,None,None,None
1031092,honzik.avcdn.net,[461|1448|1448|621|80|345|287|287|1448|1448|14...,1,-1,-1,-1,1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
1031093,prebid-server.rubiconproject.com,[552|133|41|1400|1364|246|286|74|80|303|303|92...,1,-1,-1,-1,-1,-1,-1,-1,...,1,1,1,1,1,1,1,1,1,1
1031094,zN=5gQ=,[53557|7783|60293|15697|53557|7783|60293|15697...,0,0,0,0,0,0,0,0,...,None,None,None,None,None,None,None,None,None,None

## Then we will create a separate dataframe containing the length of the first 30 packets

In [176]:
pkt_lengths = df['PKT_LENGTHS'].str.replace("[", "").str.replace("]", "").str.split("|", expand=True).replace(to_replace=[None], value=0).astype(int)
pkt_lengths

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,517,1240,1240,1231,80,287,287,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,517,1368,1368,457,457,64,614,272,31,1234,...,0,0,0,0,0,0,0,0,0,0
2,517,156,51,69,68,38,733,1024,1024,1024,...,0,0,0,0,0,0,0,0,0,0
3,463,1412,1412,1412,305,80,485,618,31,31,...,0,0,0,0,0,0,0,0,0,0
4,561,212,64,586,46,37,31,35,871,192,...,92,539,68,230,215,76,39,89,83,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031090,517,1238,1238,822,64,1238,442,179,62,31,...,0,0,0,0,0,0,0,0,0,0
1031091,212,1330,1330,1330,106,1330,589,93,51,1380,...,0,0,0,0,0,0,0,0,0,0
1031092,461,1448,1448,621,80,345,287,287,1448,1448,...,1448,1448,1448,1448,1448,1448,1448,1448,1448,517
1031093,552,133,41,1400,1364,246,286,74,80,303,...,72,72,72,76,76,72,72,1460,1309,1460
1031094,53557,7783,60293,15697,53557,7783,60293,15697,53557,13159,...,0,0,0,0,0,0,0,0,0,0

## Now we will replace the None values in our packet directions with zeros and multiply the with our packet lengths, thus finally getting a dataframe with 30 packet lengths and directions in one.

In [177]:
df = df[['TLS_SNI']].join(df.iloc[:, 2:].replace(to_replace=[None], value=0).astype(int)*pkt_lengths)
df

,TLS_SNI,0,1,2,3,4,5,6,7,8,...,20,21,22,23,24,25,26,27,28,29
0,d11-a.sdn.cz,517,-1240,-1240,-1231,80,-287,-287,0,0,...,0,0,0,0,0,0,0,0,0,0
1,firebaselogging-pa.googleapis.com,517,-1368,-1368,-457,-457,64,-614,272,-31,...,0,0,0,0,0,0,0,0,0,0
2,geller-pa.googleapis.com,517,-156,51,-69,68,-38,733,1024,1024,...,0,0,0,0,0,0,0,0,0,0
3,shepherd.avcdn.net,463,-1412,-1412,-1412,-305,80,485,-618,-31,...,0,0,0,0,0,0,0,0,0,0
4,gew4-spclient.spotify.com,561,-212,64,-586,46,37,-31,35,871,...,-92,-539,-68,-230,215,-76,39,89,-83,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031090,epwa.europarl.europa.eu,517,-1238,-1238,-822,64,1238,442,-179,-62,...,0,0,0,0,0,0,0,0,0,0
1031091,winatp-gw-weu.microsoft.com,212,-1330,-1330,-1330,-106,-1330,-589,93,-51,...,0,0,0,0,0,0,0,0,0,0
1031092,honzik.avcdn.net,461,-1448,-1448,-621,80,345,-287,-287,-1448,...,-1448,-1448,-1448,-1448,-1448,-1448,-1448,-1448,-1448,-517
1031093,prebid-server.rubiconproject.com,552,-133,-41,-1400,-1364,-246,-286,-74,80,...,72,72,72,76,76,72,72,1460,1309,1460
1031094,zN=5gQ=,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Now we want to drop the packets, which have NaN value in the TLS_SNI field, because they were probably not flow to outside world and we could not properly annonate them

In [178]:
df = df.drop(df[df['TLS_SNI'].isna()].index)
df

,TLS_SNI,0,1,2,3,4,5,6,7,8,...,20,21,22,23,24,25,26,27,28,29
0,d11-a.sdn.cz,517,-1240,-1240,-1231,80,-287,-287,0,0,...,0,0,0,0,0,0,0,0,0,0
1,firebaselogging-pa.googleapis.com,517,-1368,-1368,-457,-457,64,-614,272,-31,...,0,0,0,0,0,0,0,0,0,0
2,geller-pa.googleapis.com,517,-156,51,-69,68,-38,733,1024,1024,...,0,0,0,0,0,0,0,0,0,0
3,shepherd.avcdn.net,463,-1412,-1412,-1412,-305,80,485,-618,-31,...,0,0,0,0,0,0,0,0,0,0
4,gew4-spclient.spotify.com,561,-212,64,-586,46,37,-31,35,871,...,-92,-539,-68,-230,215,-76,39,89,-83,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031090,epwa.europarl.europa.eu,517,-1238,-1238,-822,64,1238,442,-179,-62,...,0,0,0,0,0,0,0,0,0,0
1031091,winatp-gw-weu.microsoft.com,212,-1330,-1330,-1330,-106,-1330,-589,93,-51,...,0,0,0,0,0,0,0,0,0,0
1031092,honzik.avcdn.net,461,-1448,-1448,-621,80,345,-287,-287,-1448,...,-1448,-1448,-1448,-1448,-1448,-1448,-1448,-1448,-1448,-517
1031093,prebid-server.rubiconproject.com,552,-133,-41,-1400,-1364,-246,-286,-74,80,...,72,72,72,76,76,72,72,1460,1309,1460
1031094,zN=5gQ=,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## We will create a new column called 'class' and assign a default value of 'other' to every row            
**This 'class' column will contain our annotations**

In [179]:
df['class'] = 'other'
df

,TLS_SNI,0,1,2,3,4,5,6,7,8,...,21,22,23,24,25,26,27,28,29,class
0,d11-a.sdn.cz,517,-1240,-1240,-1231,80,-287,-287,0,0,...,0,0,0,0,0,0,0,0,0,other
1,firebaselogging-pa.googleapis.com,517,-1368,-1368,-457,-457,64,-614,272,-31,...,0,0,0,0,0,0,0,0,0,other
2,geller-pa.googleapis.com,517,-156,51,-69,68,-38,733,1024,1024,...,0,0,0,0,0,0,0,0,0,other
3,shepherd.avcdn.net,463,-1412,-1412,-1412,-305,80,485,-618,-31,...,0,0,0,0,0,0,0,0,0,other
4,gew4-spclient.spotify.com,561,-212,64,-586,46,37,-31,35,871,...,-539,-68,-230,215,-76,39,89,-83,39,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031090,epwa.europarl.europa.eu,517,-1238,-1238,-822,64,1238,442,-179,-62,...,0,0,0,0,0,0,0,0,0,other
1031091,winatp-gw-weu.microsoft.com,212,-1330,-1330,-1330,-106,-1330,-589,93,-51,...,0,0,0,0,0,0,0,0,0,other
1031092,honzik.avcdn.net,461,-1448,-1448,-621,80,345,-287,-287,-1448,...,-1448,-1448,-1448,-1448,-1448,-1448,-1448,-1448,-517,other
1031093,prebid-server.rubiconproject.com,552,-133,-41,-1400,-1364,-246,-286,-74,80,...,72,72,76,76,72,72,1460,1309,1460,other
1031094,zN=5gQ=,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,other

## We can now export our TLS_SNI to csv, so we can see, which domains are present and wheter we would like to annotate them

In [180]:
df['TLS_SNI'].to_csv('domains.csv')

## We will now define the services we want to classify inside a python dictionary and classify them based on the presence of the dict key inside a TLS_SNI field

**Load our classes**

In [188]:
import json

classes = {}
with open('classes.json') as file:
    classes = json.load(file)

classes

{'github': 'github',
 'facebook': 'facebook',
 'seznam': 'seznam',
 'spotify': 'spotify',
 'fb.com': 'facebook',
 'edu.cz': 'edu.cz',
 'outlook': 'outlook',
 'mail.google': 'gmail',
 'ceskatelevize': 'ceskatelevize',
 'youtube': 'youtube',
 'reddit': 'reddit',
 'spsejecna': 'spsejecna',
 'tiktok': 'tiktok',
 'steam': 'steam',
 'epicgames': 'epicgames',
 'discord': 'discord',
 'alza.cz': 'alza',
 'nflxvideo': 'netflix',
 'moodle': 'moodle',
 'roblox': 'roblox',
 'twitch': 'twitch',
 'whatsapp': 'whatsapp',
 'mapy.cz': 'mapy.cz',
 'teams': 'teams',
 'snapchat': 'snapchat',
 'officeapps': 'office 365',
 'telegram': 'telegram'}

**Assign classes to flows we can**

In [189]:
for k, v in classes.items():
    df.loc[df['TLS_SNI'].str.contains(k), 'class'] = v

df

,TLS_SNI,0,1,2,3,4,5,6,7,8,...,21,22,23,24,25,26,27,28,29,class
0,ecs.office.com,727,-99,798,-1380,-1380,-527,-1380,-1380,74,...,0,0,0,0,0,0,0,0,0,other
1,sah-9f2a2e75-hap21.epmgmt.checkpoint.com,517,-1380,-1380,-1380,-446,126,-51,1380,788,...,0,0,0,0,0,0,0,0,0,other
2,sah-9f2a2e75-hap21.epmgmt.checkpoint.com,517,-1380,-1380,-1380,-446,126,-51,1380,788,...,0,0,0,0,0,0,0,0,0,other
3,cloud.sa.cz,517,-1380,-1380,-571,80,-287,-287,1021,-1113,...,0,0,0,0,0,0,0,0,0,other
4,cloud.sa.cz,517,-1380,-1380,-571,80,-287,-287,1030,-1109,...,0,0,0,0,0,0,0,0,0,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12338,registry.npmjs.org,659,-147,6,45,256,-1398,-1408,-1388,-1408,...,0,0,0,0,0,0,0,0,0,other
12339,pypi.org,457,-1408,6,-1408,-1408,-831,74,220,-1408,...,-24,80,0,0,0,0,0,0,0,other
12340,default.exp-tas.com,517,-99,344,-1420,-1420,-1338,614,-459,-1420,...,0,0,0,0,0,0,0,0,0,other
12341,westus-0.in.applicationinsights.azure.com,517,-99,351,-1408,-1408,-1408,-183,711,-103,...,0,0,0,0,0,0,0,0,0,other
12342,copilot-telemetry.githubusercontent.com,517,-1408,-1408,-1270,1408,541,-79,-79,-587,...,0,0,0,0,0,0,0,0,0,github

## We will now load our json for mappping numerical value to each service

In [190]:
classes_mapping = {}
with open('classes_mapping.json') as file:
    classes_mapping = json.load(file)

classes_mapping

{'1': 'other',
 '2': 'spotify',
 '3': 'facebook',
 '4': 'edu.cz',
 '5': 'outlook',
 '6': 'seznam',
 '7': 'gmail',
 '8': 'github',
 '9': 'ceskatelevize',
 '10': 'youtube',
 '11': 'reddit',
 '12': 'spsejecna',
 '13': 'tiktok',
 '14': 'steam',
 '15': 'epicgames',
 '16': 'discord',
 '17': 'alza',
 '18': 'netflix',
 '19': 'moodle',
 '20': 'roblox',
 '21': 'twitch',
 '22': 'whatsapp',
 '23': 'mapy.cz',
 '24': 'teams',
 '25': 'snapchat',
 '26': 'office 365',
 '27': 'telegram'}

## Finally we can replace the classnames in our 'class' column with the numerical values

In [191]:
for k, v in classes_mapping.items():
  df.loc[df['class'] == v, 'class'] = k

df

,TLS_SNI,0,1,2,3,4,5,6,7,8,...,21,22,23,24,25,26,27,28,29,class
0,ecs.office.com,727,-99,798,-1380,-1380,-527,-1380,-1380,74,...,0,0,0,0,0,0,0,0,0,1
1,sah-9f2a2e75-hap21.epmgmt.checkpoint.com,517,-1380,-1380,-1380,-446,126,-51,1380,788,...,0,0,0,0,0,0,0,0,0,1
2,sah-9f2a2e75-hap21.epmgmt.checkpoint.com,517,-1380,-1380,-1380,-446,126,-51,1380,788,...,0,0,0,0,0,0,0,0,0,1
3,cloud.sa.cz,517,-1380,-1380,-571,80,-287,-287,1021,-1113,...,0,0,0,0,0,0,0,0,0,1
4,cloud.sa.cz,517,-1380,-1380,-571,80,-287,-287,1030,-1109,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12338,registry.npmjs.org,659,-147,6,45,256,-1398,-1408,-1388,-1408,...,0,0,0,0,0,0,0,0,0,1
12339,pypi.org,457,-1408,6,-1408,-1408,-831,74,220,-1408,...,-24,80,0,0,0,0,0,0,0,1
12340,default.exp-tas.com,517,-99,344,-1420,-1420,-1338,614,-459,-1420,...,0,0,0,0,0,0,0,0,0,1
12341,westus-0.in.applicationinsights.azure.com,517,-99,351,-1408,-1408,-1408,-183,711,-103,...,0,0,0,0,0,0,0,0,0,1
12342,copilot-telemetry.githubusercontent.com,517,-1408,-1408,-1270,1408,541,-79,-79,-587,...,0,0,0,0,0,0,0,0,0,8

## Now we can drop the TLS_SNI column

In [192]:
df.drop(columns=['TLS_SNI'], inplace=True)
df

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,class
0,727,-99,798,-1380,-1380,-527,-1380,-1380,74,616,...,0,0,0,0,0,0,0,0,0,1
1,517,-1380,-1380,-1380,-446,126,-51,1380,788,-1103,...,0,0,0,0,0,0,0,0,0,1
2,517,-1380,-1380,-1380,-446,126,-51,1380,788,-1103,...,0,0,0,0,0,0,0,0,0,1
3,517,-1380,-1380,-571,80,-287,-287,1021,-1113,-24,...,0,0,0,0,0,0,0,0,0,1
4,517,-1380,-1380,-571,80,-287,-287,1030,-1109,1021,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12338,659,-147,6,45,256,-1398,-1408,-1388,-1408,-516,...,0,0,0,0,0,0,0,0,0,1
12339,457,-1408,6,-1408,-1408,-831,74,220,-1408,-1408,...,-24,80,0,0,0,0,0,0,0,1
12340,517,-99,344,-1420,-1420,-1338,614,-459,-1420,-39,...,0,0,0,0,0,0,0,0,0,1
12341,517,-99,351,-1408,-1408,-1408,-183,711,-103,-349,...,0,0,0,0,0,0,0,0,0,1
12342,517,-1408,-1408,-1270,1408,541,-79,-79,-587,24,...,0,0,0,0,0,0,0,0,0,8

## Export our final dataset

In [193]:
df.to_csv('agg_processed_with_classes.csv', index=False)